TOKEN = '000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/'
chat_id = '&chat_id='
text = '&text='
textplus = '[BOT] '
sendMessage = 'https://api.telegram.org/bot' + TOKEN + 'sendMessage?'
hello = 'Я могу свести тебя со случайным человеком\nЧтобы начать поиск введите /run'
